//next
import { Fragment, useState } from "react";
import Head from "next/head";

//components
import SidebarComponent from "../Admin/GlobalComponents/SidebarComponent";
import TopbarComponent from "../Admin/GlobalComponents/TopbarComponent";

//pages
import Login from "@/pages/admin/login";

//redux imports
import { connect } from "react-redux";

const AdminLayout = ({ children, isLoggedIn }) => {
  
  //sidebar
  const [collapsed, setCollapsed] = useState(false);
  const [toggled, setToggled] = useState(false);

  //sidebar-functions
  const handleCollapsedChange = () => {
    setCollapsed(!collapsed);
  };

  const handleToggleSidebar = (value) => {
    setToggled(value);
  };

  return (
    <Fragment>
      <Head>
        <title>Habitat BD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {isLoggedIn ? (
        <>
          <div className={`app ${toggled ? "toggled" : ""}`}>
            <SidebarComponent
              collapsed={collapsed}
              toggled={toggled}
              handleToggleSidebar={handleToggleSidebar}
              handleCollapsedChange={handleCollapsedChange}
            />
            <div className="content">
            <TopbarComponent handleToggleSidebar={handleToggleSidebar}/>
            <div className="holder">
              {children}
            </div>

            </div>
          </div>
        </>
      ) : (
        <Login />
      )}

      
    </Fragment>
  );
};

const mapStateToProps = (state) => {
  return {
    isLoggedIn: state.auth.token,
  };
};

export default connect(mapStateToProps)(AdminLayout);
